services:
  db:
    image: postgres:13
    container_name: postgres_db_local
    environment:
      POSTGRES_DB: my_app_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    image: fleetcard-backend:1
    container_name: fleetcard_backend_local
    ports:
      - "3000:3000"
    environment:
      DB_USERNAME: myuser
      DB_PASSWORD: mysecretpassword
      DB_NAME: my_app_db
      DB_HOST: db
      DB_PORT: 5432
      NODE_ENV: development
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: fleetcard-frontend:1
    container_name: frontend_nginx_local
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
