version: '3.8'

services:
  backend:
    build: .
    container_name: reciptocr-backend
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy # Or service_started if no HEALTHCHECK
    restart: unless-stopped
    networks:
      - app-network

  postgres:
    image: postgres:13
    container_name: reciptocr-db
    environment:
      POSTGRES_USER: Admins
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: receipt
    ports:
      - "5678:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Admin -d receipt"]
      interval: 5s
      timeout: 5s
      retries: 5

  # New db-seeder service (renamed for clarity, but can keep db-migrate if you prefer)
  db-seeder: # Renamed from db-migrate for clarity, but function is the same
    build: . # Uses the same Dockerfile as backend
    container_name: reciptocr-db-seeder
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy # Wait for DB to be ready
    networks:
      - app-network
    # *** Changed command to only run the seeder ***
    command: ["npm", "run", "db:seed"]
    restart: "no" # This container runs once and exits

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge